spring:
  application:
    name: ctl-carga-service

  profiles:
    active:
    - dev
    
#disable registering with eureka when running locally    
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

endpoints:
  routes:
    sensitive: false

server:
  port: 8082
 
---
spring:
    profiles: dev

ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 10000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true

#disable registering with eureka when running locally    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka