spring:
  application:
    name: api-gateway

  profiles:
    active:
    - dev
    
  cloud:
    config:
      enabled: false   #currently not working, there is an open bug - https://github.com/spring-cloud/spring-cloud-config/issues/829

server:
  port: 9090


zuul:
  ignoredServices: "*"
  strip-prefix: true
  sensitiveHeaders: Cookie,Set-Cookie
  prefix: /api
  routes:
    uaa:
      path: /auth/**
      serviceId: ctl-acesso-service
    carga-service:
      path: /carga-service/**
      serviceId: ctl-carga-service
    ocorrencia-service:
      path: /ocorrencia-service/**
      serviceId: ctl-ocorrencia-service
    sac-service:
      path: /sac-service/**
      serviceId: ctl-sac-service
      
logging:
  level.org.springframework.security: DEBUG

hystrix:
  command.default.execution.timeout.enabled: false

ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 20000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true

#disable registering with eureka when running locally    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
     